import { compile } from 'json-schema-to-typescript';

export type ToolEntry = {
  server: string;
  tool: {
    name: string;
    description?: string;
    inputSchema: Record<string, unknown>;
    outputSchema?: Record<string, unknown>;
  };
};

export async function generateTypes(tools: ToolEntry[]): Promise<string> {
  const toolTypes: string[] = [];

  for (const { server, tool } of tools) {
    const qualifiedName = escapeKey(`${server}/${tool.name}`);
    const inputType = await schemaToType(tool.inputSchema, `${server}_${tool.name}_input`);
    const outputType = tool.outputSchema
      ? await schemaToType(tool.outputSchema, `${server}_${tool.name}_output`)
      : 'unknown';

    // Tool description → JSDoc on the map entry
    const jsdoc = tool.description ? `    /** ${escapeJsdoc(tool.description)} */\n` : '';

    toolTypes.push(
      `${jsdoc}    '${qualifiedName}': {\n      input: ${indent(inputType, 6)};\n      output: ${indent(outputType, 6)};\n    };`
    );
  }

  return `// Auto-generated by \`toold typegen\` — do not edit
// Run \`toold typegen\` to regenerate

declare module 'toold' {
  interface TooldToolMap {
${toolTypes.join('\n')}
  }
}

export {};
`;
}

async function schemaToType(schema: Record<string, unknown>, name: string): Promise<string> {
  // json-schema-to-typescript converts `description` fields on properties
  // to JSDoc comments by default — no special config needed.
  const compiled = await compile(schema, name, {
    bannerComment: '',
    additionalProperties: false,
    unknownAny: true,
    format: false,
  });
  return extractTypeBody(compiled);
}

function extractTypeBody(compiled: string): string {
  // json-schema-to-typescript produces:
  //   /**
  //    * Schema-level description
  //    */
  //   export interface Foo {
  //     /** Property description */
  //     bar: string;
  //   }
  //
  // We extract the { ... } block, which preserves property-level JSDoc
  // comments inside the body. The schema-level description above the
  // interface is intentionally dropped — the tool's own `description`
  // (from the Tool object) serves that role on the map entry instead.
  const match = compiled.match(/\{[\s\S]*\}/);
  if (!match) return 'Record<string, unknown>';
  return match[0];
}

function escapeKey(key: string): string {
  return key.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function escapeJsdoc(text: string): string {
  // Prevent premature close of JSDoc comment
  return text.replace(/\*\//g, '*\\/');
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text.split('\n').join('\n' + pad);
}
